spring:
  application:
    name: backend-engineer-test

  datasource:
    url: jdbc:mysql://localhost:3306/rdas_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: pass001
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      pool-name: rdas-pool
      maximum-pool-size: 100

  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: create
      database-platform: org.hibernate.dialect.MySQL9Dialect

settings:
  soap-endpoint: http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso