apiVersion: apps/v1
kind: Deployment
metadata:
  name: countries-deploy
  namespace: ncba-countries
  labels:
    app.kubernetes.io/name: countries-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: countries-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: countries-api
    spec:
      containers:
        - name: countries
          image: your-dockerhub-username/backend-engineer-test:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: countries-config
                  key: SERVER_PORT
            - name: JAVA_TOOL_OPTIONS
              valueFrom:
                configMapKeyRef:
                  name: countries-config
                  key: JAVA_TOOL_OPTIONS
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /api/v1/countries
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /api/v1/countries
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
