apiVersion: v1
kind: Service
metadata:
  name: countries-svc
  namespace: ncba-countries
  labels:
    app.kubernetes.io/name: countries-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: countries-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
